name: Wonderwave CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"

      # - name: Install dependencies
        
      #   run: |
      #     ls 
      #     cd server
      #     ls
      #     cd Agence-voyage
      #     ls

      - name: Run tests
        working-directory: server
        run: |
          ls
          cd Agence-voyage
          ls
          npm test

      - name: Log in to Docker Hub
        run: docker login -u marykam1 --password-stdin

      - name: Tag and push backend image
        uses: docker/build-push-action@v4
        with:
          context: server
          push: true
          tags: marykam1/server_docker_hub:latest

      - name: Tag and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: client
          push: true
          tags: marykam1/client_docker_hub:latest
